//! Server-side multiplexer.
//!
//! Decouples ingest from response: a dispatcher loop reads requests off the
//! wire and spawns one Tokio task per request (DESIGN.md §3 "Worker Spawn").
//! Each worker runs a registered [`Handler`], wraps its result in a
//! `Envelope::Response` or `Envelope::Error`, and pushes it into an mpsc
//! channel that a dedicated writer task drains to the socket.
//!
//! Public surface:
//!   * [`Handler`] — the canonical contract handlers implement.
//!   * [`handler_fn`] — convenience adapter for closure-style registration.
//!   * [`Server`] + [`ServerBuilder`] — register handlers and run an accept loop.

use std::collections::HashMap;
use std::future::Future;
use std::sync::Arc;

use async_trait::async_trait;
use futures::sink::SinkExt;
use futures::stream::{SplitSink, StreamExt};
use tokio::net::{TcpListener, TcpStream};
use tokio::sync::mpsc;
use tokio_util::codec::Framed;
use tracing::{debug, error, trace, warn};

use crate::codec::WireCodec;
use crate::envelope::{Envelope, ErrorData, RequestData, ResponseData};
use crate::error::PatinaError;

/// Bound on the writer task's mpsc buffer. Backpressures dispatchers when the
/// socket can't drain responses fast enough.
const WRITER_CHANNEL_CAPACITY: usize = 128;

/// Wire-level status code used when a request names a method the server
/// hasn't registered. Mirrors HTTP 404 by convention.
const UNKNOWN_METHOD_CODE: u16 = 404;

/// Error returned by a [`Handler`] when business logic fails.
///
/// Distinct from [`ErrorData`] because handlers shouldn't have to know
/// (or set) the per-request `id` — the dispatcher pairs the error with the
/// request id when building the outbound `Envelope::Error`.
#[derive(Debug, Clone)]
pub struct HandlerError {
    /// HTTP-like status code surfaced to the caller as `RpcError::Remote.code`.
    pub code: u16,
    /// Human-readable message surfaced to the caller as `RpcError::Remote.message`.
    pub message: String,
}

impl HandlerError {
    pub fn new(code: u16, message: impl Into<String>) -> Self {
        Self { code, message: message.into() }
    }
}

/// Maps a [`PatinaError`] returned by a generated service dispatch into the
/// wire-level [`HandlerError`]. Application errors keep their code; transport
/// or lifecycle variants (which a handler shouldn't normally produce) collapse
/// to a generic 500.
impl From<PatinaError> for HandlerError {
    fn from(e: PatinaError) -> Self {
        match e {
            PatinaError::Remote { code, message } => HandlerError { code, message },
            other => HandlerError { code: 500, message: other.to_string() },
        }
    }
}

/// Implemented by anything the server can dispatch a request to.
///
/// Implementors hold any state they need via `&self` (DB pools, configs,
/// metrics handles) and route on `&self` data. For closure-style registration
/// in tests/demos, see [`handler_fn`].
#[async_trait]
pub trait Handler: Send + Sync + 'static {
    async fn handle(&self, payload: Vec<u8>) -> Result<Vec<u8>, HandlerError>;
}

/// Adapt an `Fn(Vec<u8>) -> impl Future<Output = Result<Vec<u8>, HandlerError>>`
/// closure into a [`Handler`]. Convenience for tests and small demos; real
/// services should implement [`Handler`] on a struct to keep state on `&self`.
pub fn handler_fn<F, Fut>(f: F) -> impl Handler
where
    F: Fn(Vec<u8>) -> Fut + Send + Sync + 'static,
    Fut: Future<Output = Result<Vec<u8>, HandlerError>> + Send + 'static,
{
    FnHandler(f)
}

struct FnHandler<F>(F);

#[async_trait]
impl<F, Fut> Handler for FnHandler<F>
where
    F: Fn(Vec<u8>) -> Fut + Send + Sync + 'static,
    Fut: Future<Output = Result<Vec<u8>, HandlerError>> + Send + 'static,
{
    async fn handle(&self, payload: Vec<u8>) -> Result<Vec<u8>, HandlerError> {
        (self.0)(payload).await
    }
}

/// Implemented by the `[Trait]Server<S>` type the `#[patina_rpc::service]`
/// macro generates. Lists the fully-qualified method names the service owns
/// (`"Trait::method"`) and routes a decoded request to the matching method.
///
/// Registered into a [`Server`] via [`ServerBuilder::add_service`], which
/// expands each method name into the underlying [`Handler`] map.
pub trait PatinaService: Send + Sync + 'static {
    /// Fully-qualified names of every method this service handles.
    fn method_names(&self) -> &'static [&'static str];

    /// Route `method` (one of [`method_names`](PatinaService::method_names))
    /// to the user's trait impl, deserializing the payload and serializing the
    /// reply. Generated by the macro as a `match` over the method name.
    ///
    /// Native async-in-trait (RPITIT) rather than `#[async_trait]`: this trait
    /// is only ever used through the generic bound `S: PatinaService`, never as
    /// `dyn PatinaService` (the trait object in play is `dyn Handler`), so it
    /// needs no vtable and pays no boxing. The `+ Send` bound is what lets the
    /// boxed [`Handler`] future in [`ServiceMethodHandler`] await it.
    fn dispatch(
        &self,
        method: &str,
        payload: Vec<u8>,
    ) -> impl Future<Output = Result<Vec<u8>, HandlerError>> + Send;
}

/// Adapter that routes one method name through a shared [`PatinaService`].
/// `add_service` registers one of these per method into the handler map, so
/// the existing per-method dispatch path is reused unchanged.
struct ServiceMethodHandler<S> {
    svc: Arc<S>,
    method: String,
}

#[async_trait]
impl<S: PatinaService> Handler for ServiceMethodHandler<S> {
    async fn handle(&self, payload: Vec<u8>) -> Result<Vec<u8>, HandlerError> {
        self.svc.dispatch(&self.method, payload).await
    }
}

/// Frozen registry of `method -> handler` pairs. Cheap to clone (handlers are
/// shared via `Arc`), so each accepted connection gets its own handle.
#[derive(Clone)]
pub struct Server {
    handlers: Arc<HashMap<String, Arc<dyn Handler>>>,
}

impl Server {
    pub fn builder() -> ServerBuilder {
        ServerBuilder::default()
    }

    /// Run until `listener.accept()` errors. Spawns one connection task per
    /// accepted socket; connection errors are logged but do not stop the loop.
    pub async fn serve(self, listener: TcpListener) -> Result<(), PatinaError> {
        loop {
            let (stream, peer) = listener.accept().await?;
            debug!(%peer, "accepted connection");
            let me = self.clone();
            tokio::spawn(async move {
                if let Err(e) = me.serve_connection(stream).await {
                    error!(error = %e, %peer, "connection ended with error");
                }
            });
        }
    }

    /// Drive a single accepted connection until the stream ends or hits a
    /// wire-layer error. Exposed for tests and bespoke server harnesses that
    /// want their own accept logic or shutdown semantics.
    pub async fn serve_connection(&self, stream: TcpStream) -> Result<(), PatinaError> {
        serve_connection_inner(self.handlers.clone(), stream).await
    }
}

/// Mutable counterpart to [`Server`]; collects handler registrations before
/// freezing them into an `Arc`-shared map.
#[derive(Default)]
pub struct ServerBuilder {
    handlers: HashMap<String, Arc<dyn Handler>>,
}

impl ServerBuilder {
    /// Register a handler under `method`. Later registrations for the same
    /// method overwrite earlier ones.
    pub fn register<H: Handler>(mut self, method: impl Into<String>, handler: H) -> Self {
        self.handlers.insert(method.into(), Arc::new(handler));
        self
    }

    /// Register every method of a macro-generated service. Each
    /// `"Trait::method"` name is wired to the service's `dispatch` match via a
    /// [`ServiceMethodHandler`]; the service itself is shared across them.
    pub fn add_service<S: PatinaService>(mut self, service: S) -> Self {
        let service = Arc::new(service);
        for name in service.method_names() {
            self.handlers.insert(
                (*name).to_string(),
                Arc::new(ServiceMethodHandler {
                    svc: service.clone(),
                    method: (*name).to_string(),
                }),
            );
        }
        self
    }

    pub fn build(self) -> Server {
        Server { handlers: Arc::new(self.handlers) }
    }
}

async fn serve_connection_inner(
    handlers: Arc<HashMap<String, Arc<dyn Handler>>>,
    stream: TcpStream,
) -> Result<(), PatinaError> {
    let framed = Framed::new(stream, WireCodec::new());
    let (sink, mut read) = framed.split();
    let (tx, rx) = mpsc::channel::<Envelope>(WRITER_CHANNEL_CAPACITY);

    let writer = tokio::spawn(writer_loop(sink, rx));
    // If this future is aborted (e.g. a caller drops the JoinHandle for the
    // accept task) before reaching the normal `writer.await` below, we still
    // need to tear down the writer task so it drops its `SplitSink` half of
    // the Framed and the underlying TCP socket actually closes — otherwise
    // the peer hangs forever waiting on a half-alive connection.
    let _writer_guard = AbortOnDrop(writer.abort_handle());

    while let Some(frame) = read.next().await {
        match frame {
            Ok(Envelope::Request(req)) => {
                let handlers = handlers.clone();
                let tx = tx.clone();
                tokio::spawn(async move {
                    let response = dispatch(handlers, req).await;
                    if tx.send(response).await.is_err() {
                        debug!("writer mpsc closed; dropping response");
                    }
                });
            }
            Ok(Envelope::Heartbeat) => trace!("heartbeat consumed"),
            Ok(other @ (Envelope::Response(_) | Envelope::Error(_))) => {
                warn!(?other, "server received non-request envelope; ignoring");
            }
            Err(e) => {
                error!(error = %e, "decode error; closing connection");
                break;
            }
        }
    }

    // Signal the writer to drain remaining responses and exit.
    drop(tx);
    let _ = writer.await;
    Ok(())
}

async fn dispatch(
    handlers: Arc<HashMap<String, Arc<dyn Handler>>>,
    req: RequestData,
) -> Envelope {
    match handlers.get(&req.method) {
        Some(handler) => match handler.handle(req.payload).await {
            Ok(bytes) => Envelope::Response(ResponseData { id: req.id, payload: bytes }),
            Err(err) => Envelope::Error(ErrorData {
                id: req.id,
                code: err.code,
                message: err.message,
            }),
        },
        None => Envelope::Error(ErrorData {
            id: req.id,
            code: UNKNOWN_METHOD_CODE,
            message: format!("unknown method: {}", req.method),
        }),
    }
}

/// RAII helper: aborts a spawned task when dropped. Used to tear down the
/// per-connection writer task if the owning `serve_connection_inner` future
/// is cancelled mid-await rather than exiting through its normal cleanup.
struct AbortOnDrop(tokio::task::AbortHandle);

impl Drop for AbortOnDrop {
    fn drop(&mut self) {
        self.0.abort();
    }
}

async fn writer_loop(
    mut sink: SplitSink<Framed<TcpStream, WireCodec>, Envelope>,
    mut rx: mpsc::Receiver<Envelope>,
) {
    while let Some(envelope) = rx.recv().await {
        if let Err(e) = sink.send(envelope).await {
            error!(error = %e, "server writer: send failed");
            break;
        }
    }
    trace!("server writer task exiting");
}
